---
- name: update apt cache
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - make
    - tcl8.5

- name: fetch latest stable redis tar
  get_url:
    url: http://download.redis.io/redis-stable.tar.gz
    dest: /tmp/redis-stable.tar.gz

- name: extract redis tar
  unarchive:
    remote_src: true
    src: /tmp/redis-stable.tar.gz
    dest: /tmp

- name: install redis
  make:
    chdir: /tmp/redis-stable
    target: install

- name: create redis group
  group:
    name: redis
    state: present
    system: yes
  
- name: create redis user
  user:
    name: redis
    group: redis
    createhome: no
    shell: /bin/false
    system: yes
    state: present

- name: create redis dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: redis
    owner: redis
  with_items:
    - /var/lib/redis
    - /etc/redis

- name: touch redis log
  file:
    path: /var/log/redis.log
    state: touch

- name: copy redis configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "templates/redis-service.conf.j2", dest: "/etc/systemd/system/redis.service" }
    - { src: "templates/redis.conf.j2", dest: "/etc/redis/redis.conf" }

- name: start redis service
  service: 
    name: redis 
    state: restarted
