---

- name: create echo user
  user:
    name: echo
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: add ssh-key to user
  authorized_key:
    user: echo
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: set proper timezone
  timezone:
    name: Europe/Amsterdam

- name: run apt update
  apt:
    update_cache: yes

- name: install necessary packages
  apt:
    name: "{{ item }}"
  with_items:
    - python3-pip
    - git
    - nginx
    - letsencrypt

- name: copy dynamodb credentials
  copy:
    src: "~/.dynamodb"
    dest: "/home/echo/.aws"