---
# checkout app and install deps

- name: checkout app from github
  git: 
    repo: git@github.com:alexraileanu/automation-shenanigans.git
    dest: "{{ application_path }}"
    accept_hostkey: True

- name: activate or create virtualenv
  shell: /usr/local/bin/virtualenv "{{ venv_path }}"

- name: install pip stuff
  pip:
    requirements: "{{ application_path }}/requirements.txt"
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3.4

- name: create service for app
  template: 
    src: echo.service.j2
    dest: /etc/systemd/system/echo.service

- name: start app service
  service: 
    name: echo 
    state: started
    enabled: yes