---
# checkout app and install deps

- name: checkout app from github
  git: 
    repo: git://github.com/alexraileanu/automation-shenanigans.git
    dest: "{{ application_path }}"
    accept_hostkey: True
    version: aws

- name: activate or create virtualenv
  shell: /usr/local/bin/virtualenv "{{ venv_path }}"

- name: install pip stuff
  pip:
    requirements: "{{ application_path }}/requirements.txt"
    virtualenv: "{{ venv_path }}"

- name: create service for app
  template: 
    src: echo.service.j2
    dest: /etc/systemd/system/echo.service

- name: ensure proper permissions for app
  file:
    path: "{{ application_path }}"
    state: directory
    owner: echo
    group: www-data
    recurse: yes

- name: start echo service
  service: 
    name: echo 
    state: started
    enabled: yes 