---
# ensure that python, virtualenv and pip are installed

- name: install python
  apt: 
    name: python3 
    state: present

- name: install pip
  apt: 
    name: python3-pip 
    state: present

- name: install virtualenv
  pip: 
    name: virtualenv