---
# install and configure nginx

- name: install nginx
  apt: 
    name: nginx 
    state: present

- name: add nginx vhost file
  template: 
    src: echo.conf.j2 
    dest: /etc/nginx/sites-enabled/echo.conf 
    validate: nginx -t -c %s
  notify: restart nginx

- name: start nginx service
  service: 
    name: nginx 
    state: restarted 
    enabled: yes